### ISSUE TITLE
Wrong flash on login failed

### ISSUE THREAD

**Issue by gimmyxd** [razvanbugariu/mentors4me-client#46]
![uploads/e0e7fd39-5624-4326-9a57-32d53b1ce3cd/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe0e7fd39-5624-4326-9a57-32d53b1ce3cd%2Fblob)

**Comment by IuresiIssabel** [comment]
There are still 2 messages and the one with not authorized should not be there.

**Comment by IuresiIssabel** [comment]
![2017-02-16 1](https://cloud.githubusercontent.com/assets/12182775/23039248/a13f43c8-f495-11e6-8968-1a9b95c60e52.png)

**Comment by IuresiIssabel** [comment]
test message for Razvan
