### ISSUE TITLE
When a new organization is created the page is not redirected

### ISSUE THREAD

**Issue by IuresiIssabel** [razvanbugariu/mentors4me-client#50]
1. Create e new organization account
2. The flash message with "account created" appear, but the page remains the same
![screenshot_5](https://cloud.githubusercontent.com/assets/12182775/22877415/fd1bc762-f1dd-11e6-8acd-4fa59f470b34.png)

**Comment by razvanbugariu** [comment]
I just made an organization accout and it work.Printed the message and then redirected to login view

**Comment by razvanbugariu** [comment]
Tested it on the current master branch and it worked. Where did you tested it? when was the last deployed made?
